name: typed_isolate
description: Easier and type-safe isolate usage with parent and child isolates
version: 5.0.0
repository: https://github.com/Levi-Lesches/typed_isolate

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  meta: ^1.15.0

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^6.0.0
